# Results will be saved to neosr/experiments/results/

name = "test_aether"
model_type = "image"
scale = 2
#use_amp = true
#compile = true

[datasets.test_1]
name = "val_1"
type = "single"
dataroot_lq = '/home/phips/Documents/dataset/BHI/BHI100/x2'
[val]
#tile = 200

[network_g]
type = "aether_small"
#type = "aether_medium"
#type = "aether_large"
fused_init = true

[path]
pretrain_network_g = '/home/phips/Documents/GitHub/neosr-fork/aether_scripts/converted_models5/aether_small_2x_int8_fused.pth' # Point to your newly fused model
